### ISSUE TITLE
not working taking for ever to load home page 

### ISSUE THREAD

**Issue by vijaykumarmanthena** [Raguggg/django-postgresql-cron-nginx-docker-compose#1]
![image](https://github.com/user-attachments/assets/e4048296-9e19-47b2-a05a-60a297d7af04)
![image](https://github.com/user-attachments/assets/1b442393-5e6f-4e5d-bbee-60729612ed6b)
and home page is still laoding

**Comment by Ragug** [comment]
you have done some mistake pls check django logs

**Comment by vijaykumarmanthena** [comment]
@Raguggg  now working good in code space but notworked on my server will check what might be the issue on the server
